name: Build 42_libft
on:
    push:
        branches: [ "main" ]
    pull_request:
jobs:
    build-42_libft:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Build and Test
              run: |
                make fclean
                make
